services:
  manager:
    build: ./manager-service
    ports:
      - "8080:8080"

  bidder:
    build: ./bidder-service
    ports:
      - "8081:8081"
    depends_on:
      - manager # Esto asegura que Manager Service inicie antes que Bidder
